name: Docker

on:
  workflow_dispatch:
    inputs:
      checkout_ref:
        required: true
        type: string
        default: 'main'
        description: 'The branch to checkout and build artifacts from. By default "main".'
      release_version:
        required: true
        type: string
        description: 'Release version number (Pattern - v#.#.# , f.e. or v3.0.0-alpha1 for pre-releases. Use prefix "v".)'

env:
  IMAGE_NAME: "bsc-staking-indexer"
  APP_REPO: "bnb-chain/bsc-staking-indexer"
  DOCKERHUB_REPOSITORY: "ghcr.io/bnb-chain/bsc-staking-indexer"



jobs:
  # Push image to GitHub Packages.
  docker-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository ${{ env.APP_REPO }} reference ${{ inputs.checkout_ref }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.APP_REPO }}
          fetch-depth: 0
          ref: ${{ inputs.checkout_ref }}
          path: 'bsc-staking-indexer'

      - name: Check if tag ${{ inputs.release_version }} already exists and create it in case perform_release is set.
        if: ${{ inputs.release_version != '' }}
        run: |
          cd bsc-staking-indexer
          if git ls-remote --exit-code --quiet --tags origin '${{ inputs.release_version }}'; then
            echo "ERROR: tag ${{ inputs.release_version }} exists and workflow is performing release. Exit."
            exit 1
          else
            echo "OK: tag ${{ inputs.release_version }} does not exists. Proceeding."
            git tag ${{ inputs.release_version }}
            git push origin ${{ inputs.release_version }}
            echo; echo "Git TAG ${{ inputs.release_version }} created and pushed."
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db ## v3.6.1


      - name: ghcr-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build image and push
        run: |
          cd bsc-staking-indexer          
          docker buildx build \
            --file ./Dockerfile \
            --build-arg GIT_TOKEN_URL=${{secrets.GIT_TOKEN_URL}} \
            --tag ${{ env.DOCKERHUB_REPOSITORY }}:${{ inputs.release_version }} \
            --tag ${{ env.DOCKERHUB_REPOSITORY }}:latest \
            --label "org.opencontainers.image.source=${{ secrets.IMAGE_SOURCE }}" \
            --label "org.opencontainers.image.revision=$(git rev-parse HEAD)" \
            --label "org.opencontainers.image.version=${{inputs.release_version }}" \
            --label "org.opencontainers.image.licenses=LGPL-3.0,GPL-3.0" \
            --push .
